name: cd

on:
  push: 
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    outputs:
      generated-tag: ${{ steps.get-image-tag.outputs.image-tag }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"
      - name: Get image tag
        id: get-image-tag
        run: echo "::set-output name=image-tag::${{ steps.login-ecr.outputs.registry }}/r2d2-image-builder:${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.get-image-tag.outputs.image-tag }}
          # This should be set to false because AWS Lambda does not supprot multi architecture image.
          provenance: false 

  deploy-to-aws-lambda:
    name: Deploy to AWS Lambda
    needs: [ build-and-push-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AWS Lambda function
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-2
          function_name: r2d2-image-builder
          image_uri: ${{ needs.build-and-push-image.outputs.generated-tag }}
    